#define IDC_STATIC -1
#define IDD_MAIN                        101
#define IDC_TEXT                        1000
#define IDC_INTERVAL                    1001
#define IDC_LIST                        1002
#define IDC_ADD                         1003
#define IDC_CLEAR                       1004
#define IDC_REMOVE                      1005
#define IDC_SHOWCOUNT                   1006
#define IDC_START                       1007
#define IDT_TYPINGTIMER                 1008
#define IDC_DELAY                       1009
